package examenlab5p2_luishenriquez;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ExamenLab5P2_LuisHenriquez extends javax.swing.JFrame {

    public ExamenLab5P2_LuisHenriquez() {
        initComponents();
        
        usuarios.add(new Civil("Juan", "Borjas", "Boro@", "Masculino", "Francisco Morazán", new Date(2002, 01, 25)));
        usuarios.add(new Civil("Carlos", "Espinal", "1234", "Masculino", "Cortés", new Date(2004, 8, 25)));
        usuarios.add(new Civil("Daniel", "Juarez", "4321", "Masculino", "Comayagua", new Date(2004, 03, 21)));
        usuarios.add(new Empleado("Ingeniero en sistemas", "Head of IT", 2, 
                "Emilio", "Cantarero", "1234", "Masculino", "Comayagua", new Date(2004, 06, 9)));
        
        for (int i = 0; i < usuarios.size(); i++) {
            int cont = 0;
            for (int j = 0; j < usuarios.size(); j++) {
                if (usuarios.get(i).getNumeroIdentidad().equals(usuarios.get(j).getNumeroIdentidad())) {
                    cont++;
                }
            }
            if (cont > 1) {
                usuarios.get(i).setNumeroIdentidad(usuarios.get(i).CalcularNumeroIdentidad(usuarios.get(i).getDepartamento(),
                        usuarios.get(i).getFechaNacimiento()));
            }
        }
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_sexo.getModel();
        modelo.addElement( "Masculino");
        modelo.addElement( "Femenino");
        
        cb_sexo.setModel(modelo);
        
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel)cb_departamento.getModel();
        modelo2.addElement( "Comayagua");
        modelo2.addElement( "Francisco Morazán");
        modelo2.addElement( "Cortés");
        
        cb_departamento.setModel(modelo2);
        
        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel)cb_usuarios.getModel();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i) instanceof Civil) {
                modelo3.addElement(usuarios.get(i).getNumeroIdentidad());
            }
        }
        cb_usuarios.setModel(modelo3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dg_empleado = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lb_bienvenidoEmpleado = new javax.swing.JLabel();
        bt_cerrarEmpleado = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pn_infoCiviles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tramites = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_infoCiviles = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_cargarInfo = new javax.swing.JButton();
        pn_modificacionCiviles = new javax.swing.JPanel();
        cb_usuarios = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        bt_modificarCivil = new javax.swing.JButton();
        tf_apellidoEditado = new javax.swing.JTextField();
        tf_contrasenaEditado = new javax.swing.JTextField();
        tf_nombreEditado = new javax.swing.JTextField();
        cb_sexo = new javax.swing.JComboBox<>();
        cb_departamento = new javax.swing.JComboBox<>();
        dg_civil = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lb_bienvenidoCivil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_tramitesPersonales = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_infoPersonal = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bt_obtenerInfoPersonal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_descripcionTramite = new javax.swing.JTextField();
        tf_nombreTramite = new javax.swing.JTextField();
        bt_agregarTramite = new javax.swing.JButton();
        bg_principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        bt_entrar = new javax.swing.JButton();
        pf_contrasena = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Completo:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_bienvenidoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_bienvenidoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lb_bienvenidoEmpleado.setText("Bienvenido: empleado");
        jPanel2.add(lb_bienvenidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        bt_cerrarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        bt_cerrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        bt_cerrarEmpleado.setText("Cerrar sesión");
        bt_cerrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cerrarEmpleadoMouseClicked(evt);
            }
        });
        bt_cerrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cerrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        pn_infoCiviles.setBackground(new java.awt.Color(204, 204, 204));

        tb_tramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre trámite", "Descripción", "Fecha", "No. Identidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_tramites);

        tb_infoCiviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "No. Identidad", "Fecha de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_infoCiviles);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Información civiles:");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tramites:");

        bt_cargarInfo.setBackground(new java.awt.Color(0, 0, 0));
        bt_cargarInfo.setForeground(new java.awt.Color(255, 255, 255));
        bt_cargarInfo.setText("Cargar información");
        bt_cargarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cargarInfoMouseClicked(evt);
            }
        });
        bt_cargarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_infoCivilesLayout = new javax.swing.GroupLayout(pn_infoCiviles);
        pn_infoCiviles.setLayout(pn_infoCivilesLayout);
        pn_infoCivilesLayout.setHorizontalGroup(
            pn_infoCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_infoCivilesLayout.createSequentialGroup()
                .addGroup(pn_infoCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_infoCivilesLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(pn_infoCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(pn_infoCivilesLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(bt_cargarInfo)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pn_infoCivilesLayout.setVerticalGroup(
            pn_infoCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_infoCivilesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_cargarInfo))
        );

        jTabbedPane2.addTab("Información civiles", pn_infoCiviles);

        pn_modificacionCiviles.setBackground(new java.awt.Color(204, 204, 204));

        cb_usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuariosItemStateChanged(evt);
            }
        });
        cb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuariosActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre:");

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Contraseña:");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Sexo:");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Departamento:");

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Apellido:");

        bt_modificarCivil.setBackground(new java.awt.Color(0, 0, 0));
        bt_modificarCivil.setForeground(new java.awt.Color(255, 255, 255));
        bt_modificarCivil.setText("Modificar");
        bt_modificarCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarCivilMouseClicked(evt);
            }
        });

        cb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_modificacionCivilesLayout = new javax.swing.GroupLayout(pn_modificacionCiviles);
        pn_modificacionCiviles.setLayout(pn_modificacionCivilesLayout);
        pn_modificacionCivilesLayout.setHorizontalGroup(
            pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_modificacionCivilesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_usuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_modificacionCivilesLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11))
                    .addGroup(pn_modificacionCivilesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tf_contrasenaEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_modificacionCivilesLayout.createSequentialGroup()
                        .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_modificacionCivilesLayout.createSequentialGroup()
                        .addComponent(tf_nombreEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_apellidoEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_modificarCivil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        pn_modificacionCivilesLayout.setVerticalGroup(
            pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_modificacionCivilesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellidoEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_contrasenaEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_modificacionCivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_modificacionCivilesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_modificarCivil)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Modificaión civiles", pn_modificacionCiviles);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 740, 380));

        javax.swing.GroupLayout dg_empleadoLayout = new javax.swing.GroupLayout(dg_empleado.getContentPane());
        dg_empleado.getContentPane().setLayout(dg_empleadoLayout);
        dg_empleadoLayout.setHorizontalGroup(
            dg_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        dg_empleadoLayout.setVerticalGroup(
            dg_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_bienvenidoCivil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_bienvenidoCivil.setForeground(new java.awt.Color(0, 0, 0));
        lb_bienvenidoCivil.setText("Bienvenido: civil");
        jPanel3.add(lb_bienvenidoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jTabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tb_tramitesPersonales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre trámite", "Descripción", "Fecha", "No. Identidad"
            }
        ));
        jScrollPane3.setViewportView(tb_tramitesPersonales);

        tb_infoPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "No. Identidad", "Fecha de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tb_infoPersonal);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Información personal:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Trámites:");

        bt_obtenerInfoPersonal.setBackground(new java.awt.Color(0, 0, 0));
        bt_obtenerInfoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        bt_obtenerInfoPersonal.setText("Obtener información");
        bt_obtenerInfoPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_obtenerInfoPersonalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(bt_obtenerInfoPersonal)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_obtenerInfoPersonal)
                .addGap(7, 7, 7))
        );

        jTabbedPane3.addTab("Información personal", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre:");

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Descripción:");

        bt_agregarTramite.setBackground(new java.awt.Color(0, 0, 0));
        bt_agregarTramite.setForeground(new java.awt.Color(255, 255, 255));
        bt_agregarTramite.setText("Enviar");
        bt_agregarTramite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarTramiteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(tf_descripcionTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(bt_agregarTramite)
                .addGap(62, 62, 62))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(tf_nombreTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_agregarTramite)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcionTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(tf_nombreTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Gestión de trámites", jPanel5);

        jPanel3.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 410));

        javax.swing.GroupLayout dg_civilLayout = new javax.swing.GroupLayout(dg_civil.getContentPane());
        dg_civil.getContentPane().setLayout(dg_civilLayout);
        dg_civilLayout.setHorizontalGroup(
            dg_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        dg_civilLayout.setVerticalGroup(
            dg_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_principal.setBackground(new java.awt.Color(255, 255, 255));
        bg_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LogIn");
        bg_principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");
        bg_principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre Completo:");
        bg_principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, -1));

        tf_nombre.setBackground(new java.awt.Color(204, 204, 204));
        tf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });
        bg_principal.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 250, 40));

        bt_entrar.setBackground(new java.awt.Color(0, 0, 0));
        bt_entrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        bg_principal.add(bt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        pf_contrasena.setBackground(new java.awt.Color(204, 204, 204));
        pf_contrasena.setForeground(new java.awt.Color(0, 0, 0));
        bg_principal.add(pf_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Usuario userin =null;
    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        String[] nombre = new String [2];
        nombre = tf_nombre.getText().split(" ");
        String contrasena = pf_contrasena.getText();
        boolean acceso = false;
        
        for (int i = 0; i < usuarios.size(); i++) {
            String nombreActual = usuarios.get(i).getNombre();
            String apellidoActual = usuarios.get(i).getApellido();
            String contrasenaActual = usuarios.get(i).getContrasena();
            
            
            if (nombre[0].equals(nombreActual) && nombre[1].equals(apellidoActual)) {
                if (pf_contrasena.getText().equals(contrasenaActual)) {
                    this.setVisible(false);
                    tf_nombre.setText("");
                    pf_contrasena.setText("");
                    acceso = true;
                    userin = usuarios.get(i);
                }
            }
        }
        
        if (!acceso) {
            JOptionPane.showMessageDialog(this, "Stranger danger.");
        } else {
            if (userin instanceof Civil) {
                lb_bienvenidoCivil.setText("Bienvenido: " + nombre[0] + " " + nombre[1]);
                dg_civil.setVisible(true);
                dg_civil.pack();
            }else{
                lb_bienvenidoEmpleado.setText("Bienvenido: " + nombre[0] + " " + nombre[1]);
                dg_empleado.setVisible(true);
                dg_empleado.pack();
            }
        }
        
        
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void bt_cerrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarEmpleadoMouseClicked
        // TODO add your handling code here:
        //Cerrar sesión empleado
        dg_empleado.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_bt_cerrarEmpleadoMouseClicked

    private void bt_cerrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cerrarEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //Cerrar sesión civil
        dg_civil.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_cargarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cargarInfoActionPerformed

    private void bt_cargarInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cargarInfoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tb_infoCiviles.getModel();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i) instanceof Civil) {
                Usuario usuarioActual = usuarios.get(i);
                Object[] arr1 = new Object[3];
                String nombreCompleto = usuarioActual.getNombre() + " " + usuarioActual.getApellido();
                arr1[0] = nombreCompleto;
                arr1[1] = usuarioActual.getNumeroIdentidad();
                arr1[2] = usuarioActual.getFechaNacimiento();
                dtm.addRow(arr1);
                tb_infoCiviles.setModel(dtm);
            }
        }
        
        DefaultTableModel dtm2 = (DefaultTableModel)tb_tramites.getModel();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i) instanceof Civil) {
                Usuario usuarioActual = usuarios.get(i);
                for (int j = 0; j < ((Civil)usuarioActual).getTramites().size(); j++) {
                    Object[] arr1 = new Object[4];
                    arr1[0] = ((Civil) usuarioActual).getTramites().get(j).getNombre();
                    arr1[1] = ((Civil) usuarioActual).getTramites().get(j).getDescripcion();
                    arr1[2] = usuarioActual.getFechaNacimiento();
                    arr1[3] = usuarioActual.getNumeroIdentidad();
                    dtm2.addRow(arr1);
                }
                tb_tramites.setModel(dtm2);
            }
        }
        
    }//GEN-LAST:event_bt_cargarInfoMouseClicked

    private void cb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuariosActionPerformed

    private void cb_usuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuariosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuariosItemStateChanged

    private void bt_modificarCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarCivilMouseClicked
        // TODO add your handling code here:
        String numeroIdentidadActual = cb_usuarios.getSelectedItem().toString();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNumeroIdentidad().equals(numeroIdentidadActual)) {
                usuarios.get(i).setApellido(tf_apellidoEditado.getText());
                usuarios.get(i).setNombre(tf_nombreEditado.getText());
                usuarios.get(i).setContrasena(tf_contrasenaEditado.getText());
                usuarios.get(i).setSexo(cb_sexo.getSelectedItem().toString());
                usuarios.get(i).setDepartamento(cb_departamento.getSelectedItem().toString());
                usuarios.get(i).setFechaNacimiento(jCalendar1.getDate());
            }
        }
        
        tf_apellidoEditado.setText("");
        tf_nombreEditado.setText("");
        tf_contrasenaEditado.setText("");
        JOptionPane.showMessageDialog(this, "Cambio realizado exitosamente.");
    }//GEN-LAST:event_bt_modificarCivilMouseClicked

    private void bt_agregarTramiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarTramiteMouseClicked
        // TODO add your handling code here:
        ((Civil) userin).getTramites().add(new Tramite(tf_nombreTramite.getText(), 
                tf_descripcionTramite.getText(), new Date(), userin.getNumeroIdentidad()));
        
        tf_descripcionTramite.setText("");
        tf_nombreTramite.setText("");
        
        JOptionPane.showMessageDialog(this, "Trámite registrado correctamente.");
    }//GEN-LAST:event_bt_agregarTramiteMouseClicked

    private void cb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sexoActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void bt_obtenerInfoPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_obtenerInfoPersonalMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb_model = (DefaultTableModel) tb_infoPersonal.getModel();

        Object[] arr1 = new Object[3];
        String nombreCompleto = userin.getNombre() + " " + userin.getApellido();
        arr1[0] = nombreCompleto;
        arr1[1] = userin.getNumeroIdentidad();
        arr1[2] = userin.getFechaNacimiento();
        tb_model.addRow(arr1);
        tb_infoPersonal.setModel(tb_model);
        
        DefaultTableModel tb_model2 = (DefaultTableModel) tb_tramitesPersonales.getModel();
        
        for (int i = 0; i < ((Civil) userin).getTramites().size(); i++) {
            Object[] arr2 = new Object[4];
            arr2[0] = ((Civil) userin).getTramites().get(i).getNombre();
            arr2[1] = ((Civil) userin).getTramites().get(i).getDescripcion();
            arr2[2] = ((Civil) userin).getTramites().get(i).getFechaSolicitud();
            arr2[3] = userin.getNumeroIdentidad();
            tb_model2.addRow(arr2);
        }
        tb_tramitesPersonales.setModel(tb_model2);
        
        
    }//GEN-LAST:event_bt_obtenerInfoPersonalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_LuisHenriquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_LuisHenriquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_LuisHenriquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_LuisHenriquez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenLab5P2_LuisHenriquez().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_principal;
    private javax.swing.JButton bt_agregarTramite;
    private javax.swing.JButton bt_cargarInfo;
    private javax.swing.JButton bt_cerrarEmpleado;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_modificarCivil;
    private javax.swing.JButton bt_obtenerInfoPersonal;
    private javax.swing.JComboBox<String> cb_departamento;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JDialog dg_civil;
    private javax.swing.JDialog dg_empleado;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lb_bienvenidoCivil;
    private javax.swing.JLabel lb_bienvenidoEmpleado;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JPanel pn_infoCiviles;
    private javax.swing.JPanel pn_modificacionCiviles;
    private javax.swing.JTable tb_infoCiviles;
    private javax.swing.JTable tb_infoPersonal;
    private javax.swing.JTable tb_tramites;
    private javax.swing.JTable tb_tramitesPersonales;
    private javax.swing.JTextField tf_apellidoEditado;
    private javax.swing.JTextField tf_contrasenaEditado;
    private javax.swing.JTextField tf_descripcionTramite;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreEditado;
    private javax.swing.JTextField tf_nombreTramite;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<Usuario> usuarios = new ArrayList();

}
